### ISSUE TITLE
where is the api.sync() method?

### ISSUE THREAD

**Issue by woodgear** [Doist/todoist-api-python#52]
## Question description
it says 
> After that we can just do a sync by calling api.sync(), and we can access the user's projects through the api.state object, so for projects that is: api.state['projects'].

> Note that the Python library always does incremental syncs under the hood, so there's no reason to worry about them if you use it.

in https://developer.todoist.com

but i could not find it.

**Comment by nikhilmaddirala** [comment]
Came here for the same question lol - anyone know the answer?

**Comment by lefcha** [comment]
The old and now deprecated [Doist/todoist-python](https://github.com/Doist/todoist-python) library was based on the Sync API. Nowadays we only provide this REST API based Python library that this issue is part of (ie. [Doist/todoist-api-python](https://github.com/Doist/todoist-api-python)).

I don't think there's any mention of Python in the [developer.todoist.com/sync/](https://developer.todoist.com/sync/v9/#overview) page. You can see examples of the REST API based library at the REST API documentation page: [developer.todoist.com/rest/](https://developer.todoist.com/rest/v2/?python#overview).

**Comment by nikhilmaddirala** [comment]
@lefcha You're right. Looks like @woodgear and I were looking at a deprecated version of the sync api documentation which mentions the python api.sync() call: https://developer.todoist.com/sync/v8/#overview
